matrix:
  include:
    - language: scala
      scala:
        - 2.11.7
      jdk:
        - openjdk8
      script:
        - echo "Scala test"

        
    - language: go
      go:
        - 1.x
        - master 

